apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: {{ include "springboot-tekton.fullname" . }}-pipeline
spec:
  workspaces:
  - name: local-maven-repo
  - name: exchange-area
  resources:
  - name: {{ include "springboot-tekton.fullname" . }}-source
    type: git
  - name: {{ include "springboot-tekton.fullname" . }}-templates
    type: git
  - name: {{ include "springboot-tekton.fullname" . }}-image
    type: image
  ####
  tasks:
  - name: maven-and-image-build
    taskRef: 
      name: maven-and-image-build
    resources:
      inputs:
      - name: source
        resource: {{ include "springboot-tekton.fullname" . }}-source
      outputs:
      - name: image
        resource: {{ include "springboot-tekton.fullname" . }}-image
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: output-area
      workspace: exchange-area
  ####
  - name: deploy-to-stage
    taskRef:
      name: deploy
    resources:
      inputs:
      - name: templates
        resource: {{ include "springboot-tekton.fullname" . }}-templates
    runAfter:
      - maven-and-image-build
    params:
    - name: fromNamespace
      value: {{ .Values.deploy.namespace.prefix }}-cicd-paolocarta
    - name: toNamespace
      value: {{ .Values.deploy.namespace.prefix }}-stage-paolocarta  
    - name: imageStream
      value: {{ include "springboot-tekton.fullname" . }} 
    - name: deployment
      value: {{ include "springboot-tekton.fullname" . }}
    workspaces:
    - name: output-area
      workspace: exchange-area
  ####
  # - name: deploy-to-prod
  #   taskRef:
  #     name: deploy
  #   conditions:
  #     - conditionRef: "verify"
  #       params:
  #         - name: "path"
  #           value: "$(params.path)"
  #   resources:
  #     inputs:
  #     - name: templates
  #       resource: {{ include "springboot-tekton.fullname" . }}-templates
  #   runAfter:
  #     - deploy-to-stage
  #   params:
  #   - name: fromNamespace
  #     value: {{ .Values.deploy.namespace.prefix }}-stage-paolocarta
  #   - name: toNamespace
  #     value: {{ .Values.deploy.namespace.prefix }}-prod-paolocarta  
  #   - name: tag
  #     value: latest 
  #   - name: imageStream
  #     value: {{ include "springboot-tekton.fullname" . }} 
  #   - name: deployment
  #     value: {{ include "springboot-tekton.fullname" . }}