apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: deploy
spec:
  params:
    - description: The namespace we are tagging from
      name: fromNamespace
      type: string
    - description: The namespace we are tagging to
      name: toNamespace
      type: string
    - description: The imageStream
      name: imageStream
      type: string
    - description: the deployment
      name: deployment
      type: string
  resources:
    inputs:
      - name: templates
        type: git
  workspaces:
    - name: output-area
  steps:
    - name: update-deployment-from-template
      image: quay.io/openshift-pipeline/openshift-cli:latest
      workingDir: /workspace/templates/manifests
      script: |
        #!/usr/bin/env bash
        echo "Updating namespace $(params.toNamespace)"
        oc process \
          -f deployment.yml \
          -p "APPLICATION_NAME=$(params.imageStream)" \
          -p "IMAGE_TAG=$(cat /workspace/output-area/version)" \
          -p "NAMESPACE=$(params.toNamespace)" \
          -p READINESS_PATH="/health" \
          -p READINESS_RESPONSE="status.:.UP" \
          | oc apply -f -
    - name: tag-image
      image: quay.io/openshift-pipeline/openshift-cli:latest
      command: ["oc"]
      args:
        - tag
        - "$(params.fromNamespace)/$(params.imageStream):$(cat /workspace/output-area/version)"
        - "$(params.toNamespace)/$(params.imageStream):$(cat /workspace/output-area/version)"
    - name: verify-deployment
      image: quay.io/openshift-pipeline/openshift-cli:latest
      command: ["oc"]
      args:
        - rollout
        - status
        - "dc/$(params.deployment)"
        - -n
        - "$(params.toNamespace)"